=== MISP/misp-taxonomies/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-taxonomies",
  "id": "https://www.github.com/MISP/misp-taxonomies/schema.json",
  "defs": {
    "non-empty-string": {
      "type": "string",
      "minLength": 1
    },
    "entry": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "numerical_value": {
            "type": "number"
          },
          "expanded": {
            "$ref": "#/defs/non-empty-string"
          },
          "description": {
            "$ref": "#/defs/non-empty-string"
          },
          "colour": {
            "$ref": "#/defs/non-empty-string"
          },
          "value": {
            "$ref": "#/defs/non-empty-string"
          },
          "uuid": {
            "$ref": "#/defs/non-empty-string"
          },
          "required": [
            "value"
          ]
        }
      }
    },
    "values": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "entry": {
            "$ref": "#/defs/entry"
          },
          "predicate": {
            "$ref": "#/defs/non-empty-string"
          },
          "uuid": {
            "$ref": "#/defs/non-empty-string"
          }
        },
        "required": [
          "predicate"
        ]
      }
    },
    "predicates": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "numerical_value": {
            "type": "number"
          },
          "colour": {
            "$ref": "#/defs/non-empty-string"
          },
          "description": {
            "$ref": "#/defs/non-empty-string"
          },
          "expanded": {
            "$ref": "#/defs/non-empty-string"
          },
          "value": {
            "$ref": "#/defs/non-empty-string"
          },
          "exclusive": {
            "type": "boolean"
          },
          "uuid": {
            "$ref": "#/defs/non-empty-string"
          },
          "required": [
            "value"
          ]
        }
      }
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "integer"
    },
    "description": {
      "$ref": "#/defs/non-empty-string"
    },
    "expanded": {
      "$ref": "#/defs/non-empty-string"
    },
    "namespace": {
      "$ref": "#/defs/non-empty-string"
    },
    "uuid": {
      "$ref": "#/defs/non-empty-string"
    },
    "exclusive": {
      "type": "boolean"
    },
    "type": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "org",
          "user",
          "attribute",
          "event"
        ]
      }
    },
    "refs": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "#/defs/non-empty-string"
      }
    },
    "predicates": {
      "$ref": "#/defs/predicates"
    },
    "values": {
      "$ref": "#/defs/values"
    }
  },
  "required": [
    "namespace",
    "description",
    "version",
    "predicates"
  ]
}

=== MISP/misp-taxonomies/financial/machinetag.json
{
  "predicates": [
    {
      "description": "Categories and types of services in the financial scope. An entity can be tag with one or more categories or types of services.",
      "expanded": "Categories and types of services",
      "value": "categories-and-types-of-services",
      "uuid": "33d42180-32df-54c4-b85a-ac76e3c3b27e"
    },
    {
      "description": "Geographical footprint of the financial entity.",
      "expanded": "Geographical footprint",
      "value": "geographical-footprint",
      "uuid": "1d703f85-e44e-5bbc-b8e2-9fc6f3e564a7"
    },
    {
      "description": "Online exposition of the financial entity.",
      "expanded": "Online exposition",
      "value": "online-exposition",
      "uuid": "24cae7a9-e62b-5af9-b011-2d8f3e50be2a"
    },
    {
      "description": "Physical presence of the financial entity.",
      "expanded": "Physical presence",
      "value": "physical-presence",
      "uuid": "840e8b26-af26-589b-86d6-b7e2db6bcdd4"
    },
    {
      "description": "Services provided by the financial entity.",
      "expanded": "Services",
      "value": "services",
      "uuid": "41a4f778-6669-55fd-9e75-e1a7b402e77a"
    }
  ],
  "values": [
    {
      "predicate": "categories-and-types-of-services",
      "entry": [
        {
          "value": "banking",
          "expanded": "Banking",
          "description": "Financial entity described or/and regulated as banking.",
          "uuid": "807559a3-8230-559d-941e-d455c4ca0d59"
        },
        {
          "value": "private",
          "expanded": "Private",
          "description": "Financial entity engaged in private banking.",
          "uuid": "4dd4fcd3-fffd-5de6-8ab1-04c495acf4f4"
        },
        {
          "value": "retail",
          "expanded": "Retail",
          "description": "Financial entity engaged in retail banking.",
          "uuid": "1aa037a5-3b66-5b02-8b9b-7f79fe2c5f83"
        },
        {
          "value": "custodian-banking",
          "expanded": "Custodian banking",
          "description": "Financial entity having physical possessions of clients financial assets or instruments.",
          "uuid": "f287bc95-09dc-5da7-96ab-eb31392e6b28"
        },
        {
          "value": "financial-market-infrastructure",
          "expanded": "Financial market infrastructure",
          "description": "Financial market infrastructure such as stock exchange, CSD",
          "uuid": "b7ed8e62-2c2b-5327-aab8-774e4e8ddb2f"
        },
        {
          "value": "asset-management",
          "expanded": "Asset management",
          "description": "Financial entity managing financial assets on behalf of others.",
          "uuid": "036fc7be-f816-5817-aa6b-e6e99b7ce17b"
        },
        {
          "value": "it-provider",
          "expanded": "IT provider",
          "description": "IT provider supporting financial entities and regulated in the financial legal framework (such as support PFS in Luxembourg).",
          "uuid": "07a13b36-f9ab-599b-abde-016e356d9c5f"
        },
        {
          "value": "e-money-and-payment",
          "expanded": "e-money and payment",
          "description": "Financial entity managing electronic money as alternative to cash payment. (EU directive - Directive 2009/110/EC)",
          "uuid": "7c438638-3603-5bc9-82ed-764d9966a217"
        },
        {
          "value": "other",
          "expanded": "Other",
          "description": "Other entity classified as financial entity with other activities not defined in this taxonomy.",
          "uuid": "744ac459-e2fc-5cf2-8042-8229cd04ab8c"
        }
      ]
    },
    {
      "predicate": "geographical-footprint",
      "entry": [
        {
          "value": "client-coverage-local",
          "expanded": "Client coverage is local",
          "description": "Client and customer coverage is local to the financial entity (such as a country).",
          "uuid": "ce6c4a74-bcc4-5bef-aa7a-ec22a798888c"
        },
        {
          "value": "client-coverage-eu",
          "expanded": "Client coverage in EU",
          "description": "Client and customer coverage is limited to the European Union.",
          "uuid": "369fdd26-364c-5341-82bb-c5e4a1dd7679"
        },
        {
          "value": "client-coverage-worldwide",
          "expanded": "Client coverage is worldwide",
          "description": "Client and customer coverage is worldwide.",
          "uuid": "226de167-a846-56fb-998f-4c204f979774"
        },
        {
          "value": "corporate-structure-local",
          "expanded": "Corporate structure is local",
          "description": "Corporate structure is local to the financial entity (such as a country).",
          "uuid": "57e96e1f-7686-5b9f-9e41-cdc9b8537cb6"
        },
        {
          "value": "corporate-structure-eu",
          "expanded": "Corporate structure in EU",
          "description": "Corporate structure is located in the European Union.",
          "uuid": "55fc7082-2975-57a3-916a-58da5e16b386"
        },
        {
          "value": "corporate-structure-worldwide",
          "expanded": "Corporate structure is worldwide",
          "description": "Corporate structure is located worldwide.",
          "uuid": "90c58868-babf-5293-8bf9-b1750d5d833f"
        }
      ]
    },
    {
      "predicate": "online-exposition",
      "entry": [
        {
          "value": "limited",
          "expanded": "Limited",
          "description": "Online presence of the financial entity is limited such as just a public web server and/or email services.",
          "uuid": "381b1614-2827-5d35-9d13-eb134ff3ad02"
        },
        {
          "value": "extended",
          "expanded": "Extended",
          "description": "Online presence of the financial entity is extended with online services for the clients and customers but still with a physical presence.",
          "uuid": "e2ffbe9b-ba28-534a-8450-281f03d8bba9"
        },
        {
          "value": "crucial",
          "expanded": "Crucial",
          "description": "Online presence of the financial entity is crucial and business depends on online presence, extensive use of cloud computing, APIs, etc.",
          "uuid": "49a6b3fe-d4c2-50ff-a9d8-9573ab7455a7"
        }
      ]
    },
    {
      "predicate": "physical-presence",
      "entry": [
        {
          "value": "atm",
          "expanded": "Automated teller machines",
          "description": "The financial entity owns and/or operates automated teller machines (ATM).",
          "uuid": "bb88598e-48f5-5726-89d3-f4bbbe39cde6"
        },
        {
          "value": "pos",
          "expanded": "Point of sale terminals",
          "description": "The financial entity owns and/or operates point of sale terminals (POS).",
          "uuid": "2491e522-cc5e-5cd8-9d1f-07576007669b"
        }
      ]
    },
    {
      "predicate": "services",
      "entry": [
        {
          "value": "settlement",
          "expanded": "Settlement",
          "description": "A financial entity providing settlement services.",
          "uuid": "e20463d3-908d-50d7-bea7-400aef82717c"
        },
        {
          "value": "collateral-management",
          "expanded": "Collatoral management",
          "description": "A financial entity providing collateral management services.",
          "uuid": "88967c05-2af9-5a71-afc1-719fb0c00787"
        },
        {
          "value": "listing-operation-of-trading-platform",
          "expanded": "Listing and operation of trading platform",
          "description": "A financial entity providing listing and operation of trading platform.",
          "uuid": "f179ad2b-0b95-55bd-b915-1aec633fb8c2"
        },
        {
          "value": "credit-granting",
          "expanded": "Credit granting",
          "description": "A financial entity providing credit granting.",
          "uuid": "2cb6cc84-2870-52df-99a9-b2f525010913"
        },
        {
          "value": "deposit-management",
          "expanded": "Deposit management",
          "description": "A financial entity providing deposit management.",
          "uuid": "f6ce17f4-4a2f-50f5-8b80-b69934736af0"
        },
        {
          "value": "custodian-banking",
          "expanded": "Custodian banking",
          "description": "A financial entity providing custodian banking.",
          "uuid": "722421a8-19a6-5ffa-9c61-4fb93a4954c1"
        },
        {
          "value": "payment-services",
          "expanded": "Payment services",
          "description": "A financial entity providing payment services.",
          "uuid": "69e8eb7f-2ff1-54c4-94b9-46db0208c2b0"
        },
        {
          "value": "investment-services",
          "expanded": "Investment services",
          "description": "A financial entity providing investment services.",
          "uuid": "7bc64089-2c6c-5f74-b2e0-456a1ee37ec0"
        }
      ]
    }
  ],
  "version": 7,
  "description": "Financial taxonomy to describe financial services, infrastructure and financial scope.",
  "expanded": "Financial",
  "namespace": "financial",
  "uuid": "8b761314-6385-51bc-81e9-8030bb348d1a"
}

=== MISP/misp-taxonomies/dhs-ciip-sectors/machinetag.json
{
  "namespace": "dhs-ciip-sectors",
  "description": "DHS critical sectors as in https://www.dhs.gov/critical-infrastructure-sectors",
  "version": 2,
  "predicates": [
    {
      "value": "DHS-critical-sectors",
      "expanded": "DHS critical sectors",
      "uuid": "66ff7324-346f-5980-929b-e7d5f6249def"
    },
    {
      "value": "sector",
      "expanded": "Sector",
      "uuid": "88522b7a-3a2f-50a3-a157-e41b23d07b1d"
    }
  ],
  "values": [
    {
      "predicate": "DHS-critical-sectors",
      "entry": [
        {
          "value": "chemical",
          "expanded": "Chemical",
          "uuid": "6389e62c-833e-53e0-91fd-626d9fb4b857"
        },
        {
          "value": "commercial-facilities",
          "expanded": "Commercial Facilities",
          "uuid": "2db334dc-c2de-576a-9bec-e395451fc7ae"
        },
        {
          "value": "communications",
          "expanded": "Communications",
          "uuid": "2b34a53b-3520-5278-84f6-d97f220c9bd9"
        },
        {
          "value": "critical-manufacturing",
          "expanded": "Critical Manufacturing",
          "uuid": "4901dfce-545f-59d4-b977-304a619583e3"
        },
        {
          "value": "dams",
          "expanded": "Dams",
          "uuid": "af1aebcc-d813-5409-a315-f54a18e5825f"
        },
        {
          "value": "dib",
          "expanded": "Defense Industrial Base",
          "uuid": "7d1fa2ca-55a2-5614-88d2-f1b5313d2d27"
        },
        {
          "value": "emergency-services",
          "expanded": "Emergency services",
          "uuid": "de073614-dcc5-5560-a2fd-c74f5ebb9410"
        },
        {
          "value": "energy",
          "expanded": "energy",
          "uuid": "1b715e25-8bf8-5d34-82bb-a21954d557c5"
        },
        {
          "value": "financial-services",
          "expanded": "Financial Services",
          "uuid": "7aeef16b-425e-58a0-acaa-71e38a083f92"
        },
        {
          "value": "food-agriculture",
          "expanded": "Food and Agriculture",
          "uuid": "570ca0e5-c1aa-5ddb-b21d-b7d1c7daa4ad"
        },
        {
          "value": "government-facilities",
          "expanded": "Government Facilities",
          "uuid": "4000b997-acc7-57fe-9f2a-90a5348d9d3e"
        },
        {
          "value": "healthcare-public",
          "expanded": "Healthcare and Public Health",
          "uuid": "748b0b53-a712-5c06-a862-ac01b0768083"
        },
        {
          "value": "it",
          "expanded": "Information Technology",
          "uuid": "9cd4b903-7f29-5701-a4eb-a50006d31255"
        },
        {
          "value": "nuclear",
          "expanded": "Nuclear",
          "uuid": "ca1633d3-88a9-5d4c-9509-226548c9fdb5"
        },
        {
          "value": "transport",
          "expanded": "Transportation Systems",
          "uuid": "1328b150-e53e-5f9f-9491-325fdeb686f5"
        },
        {
          "value": "water",
          "expanded": "Water and water systems",
          "uuid": "c4a60ab3-939d-5478-8c6d-82b0859bf869"
        }
      ]
    }
  ],
  "uuid": "cd328fbd-1e67-59e0-aeb7-dc7ea28b64e5"
}

=== MISP/misp-taxonomies/vulnerability/machinetag.json
{
  "namespace": "vulnerability",
  "expanded": "vulnerability",
  "description": "A taxonomy for describing vulnerabilities (software, hardware, or social) on different scales or with additional available information.",
  "version": 3,
  "predicates": [
    {
      "value": "sighting",
      "expanded": "Sighting",
      "description": "Sighting information related to the vulnerability.",
      "uuid": "7de57a84-5345-5bf3-8d06-92f6b8a7836a"
    },
    {
      "value": "exploitability",
      "expanded": "Exploitability",
      "description": "Quantification of attack exploitability, providing a level of exploitation for the identified vulnerability.",
      "exclusive": true,
      "uuid": "ee58b264-5030-5e82-a092-09bf2e883c5d"
    },
    {
      "value": "information",
      "expanded": "Information",
      "description": "Complementary information related to the vulnerability.",
      "uuid": "9704e9e9-5a94-51a2-ae1b-4bb9edbe4e0d"
    }
  ],
  "values": [
    {
      "predicate": "sighting",
      "entry": [
        {
          "value": "seen",
          "expanded": "Seen",
          "description": "The vulnerability was mentioned, discussed, or seen somewhere by the user.",
          "uuid": "1f91a1b6-bd7e-5922-b11c-7b9b9d2a9bcf"
        },
        {
          "value": "confirmed",
          "expanded": "Confirmed",
          "description": "The vulnerability is confirmed from an analyst perspective.",
          "uuid": "ffe81c1b-c31e-59a2-8d6d-6cc22c517255"
        },
        {
          "value": "exploited",
          "expanded": "Exploited",
          "description": "This vulnerability was exploited and seen by the user reporting the sighting.",
          "uuid": "2fb7da28-aeb5-5f26-bcaf-b24fe80d386e"
        },
        {
          "value": "patched",
          "expanded": "Patched",
          "description": "This vulnerability was successfully patched by the user reporting the sighting.",
          "uuid": "d610dcf2-7b0a-5d4b-82e9-4601a6ea7f1b"
        },
        {
          "value": "not-exploited",
          "expanded": "Not exploited",
          "description": "This vulnerability was not exploited or seen by the user reporting the sighting.",
          "uuid": "27188462-f6b7-52c4-9918-615b9e29adc6"
        },
        {
          "value": "not-confirmed",
          "expanded": "Not confirmed",
          "description": "The user expresses doubt about the veracity of the vulnerability.",
          "uuid": "d69960df-db59-5d1b-98d2-ff37761f01a3"
        },
        {
          "value": "not-patched",
          "expanded": "Not patched",
          "description": "This vulnerability was not successfully patched by the user reporting the sighting.",
          "uuid": "29b5512c-8a55-5ca8-93ba-567a6ab30e12"
        }
      ]
    },
    {
      "predicate": "exploitability",
      "entry": [
        {
          "value": "industrialised",
          "expanded": "Industrialised",
          "description": "Existing vulnerability with detailed attack methods; multiple tools are available for exploitation.",
          "uuid": "7a758b62-7446-58e0-9f48-82a9e5df80b9"
        },
        {
          "value": "customised",
          "expanded": "Customised",
          "description": "Existing vulnerability with a detailed attack approach and one known custom tool available for exploitation.",
          "uuid": "e5cfbe4c-3467-5066-ba32-e705f9b013f7"
        },
        {
          "value": "documented",
          "expanded": "Documented",
          "description": "Existing vulnerability is documented with an attack approach, but tools for exploitation are not available.",
          "uuid": "c03650db-1018-5c03-a559-d21b14d6720e"
        },
        {
          "value": "theoretical",
          "expanded": "Theoretical",
          "description": "Publication describes a theoretical but no actual vulnerability is reported.",
          "uuid": "2113bfbd-08ff-5835-a8f6-fa3f704bb594"
        }
      ]
    },
    {
      "predicate": "information",
      "entry": [
        {
          "value": "PoC",
          "expanded": "Proof-of-Concept",
          "description": "Reference to a proof-of-concept for exploiting the vulnerability.",
          "uuid": "83de9a0b-00c4-5919-b2d4-1aa9e0e64a39"
        },
        {
          "value": "remediation",
          "expanded": "Remediation",
          "description": "Remediation to limit or block the exploitability of the vulnerability.",
          "uuid": "28bf7bb3-3642-5715-9b7d-14eb2f855a13"
        },
        {
          "value": "annotation",
          "expanded": "Annotation",
          "description": "Annotation or clarification to a vulnerability.",
          "uuid": "c7440a31-0e85-545c-a333-be3fa031df48"
        }
      ]
    }
  ],
  "uuid": "bb0e5c42-76ba-595f-99e8-f3bf9c31fc98"
}
